import { Poppins } from "next/font/google";
import "./globals.css"

const poppins_init = Poppins({
  subsets: [],
  variable: "--font-poppins",
  weight: ["300", "400"],
});

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins_init.variable}>{children}</body>
    </html>
  );
}
